# fly.toml app configuration file generated for templates-bitter-feather-7630 on 2024-12-01T22:35:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'templates-bitter-feather-7630'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
